# Generated by Django 2.2.2 on 2019-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='visitors',
        ),
        migrations.AddField(
            model_name='event',
            name='visitors_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
