# Generated by Django 2.2.2 on 2019-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
