# Generated by Django 2.2.2 on 2019-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190912_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
