# Generated by Django 2.2.2 on 2019-09-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190908_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
