# Generated by Django 2.2.2 on 2019-09-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190908_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='visitors_count',
        ),
    ]
