# Generated by Django 2.2.2 on 2019-09-09 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20190909_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='followers',
        ),
        migrations.AddField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='following',
        ),
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
