# Generated by Django 2.2.2 on 2019-09-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190909_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='following',
        ),
    ]
